server.port: 8081

ribbon:
  eureka:
    enabled: false

cityApi:
  ribbon:
    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
    listOfServers: localhost:8080

spring.cache.cache-names: cityById
spring.cache.caffeine.spec: expireAfterAccess=10s